name: Deploy Flask API with Docker on Apache

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Copy project files to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@82.25.107.5 "mkdir -p ~/yagnik-ai-api"
        scp -r . root@82.25.107.5:~/yagnik-ai-api

    - name: Build & Run Docker container on VPS
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no root@82.25.107.5 << 'EOF'
          cd ~/yagnik-ai-api
          docker stop flaskrestapi || true
          docker rm flaskrestapi || true
          docker build -t flaskrestapi .
          docker run -d -p 5001:5000 --name flaskrestapi \
            -e GROQ_API_KEY="${GROQ_API_KEY}" \
            -e API_BEARER_TOKEN="${API_BEARER_TOKEN}" \
            flaskrestapi
        EOF
